services:
  - type: web
    name: removebg-bot
    env: python
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
